apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: docker.io/capr1/ks-guestbook-demo@sha256:ba5b452e2111a549b30cba28a52d883a57b2a69e8bb7042466d7f09944cc89df
        name: guestbook-ui
        imagePullPolicy: Always
        ports:
        - containerPort: 80
